import type { Consult, ConsultKind, ConsultChannel } from "@/lib/consult/types";
import { summarizeConsult, stampFor } from "@/lib/consult/summarize";
import { clients } from "@/lib/mock/clients";
import { seededRandom, absolute } from "@/lib/utils";

/**
 * Seeded consult history.
 *
 * The raw notes below are written the way coaches actually type mid-conversation
 * — fragments, shorthand, no punctuation discipline. That is deliberate: the
 * summarizer has to earn its keep on realistic input, and a demo that only works
 * on tidy prose proves nothing.
 *
 * Summaries are generated by running the real summarizer over these notes at
 * module load, so what the demo displays is genuinely the engine's output, not
 * hand-written text pretending to be.
 */

const NOTE_TEMPLATES: { kind: ConsultKind; channel: ConsultChannel; notes: string }[] = [
  {
    kind: "Coach consult",
    channel: "In person",
    notes: `weighed in at 214, down 3.2 from last month
body fat scan 24.1% - down from 26
says energy is way better in the mornings now, still crashes around 3pm
sleep is the issue - waking up 2-3x a night, says he's been stressed with work
training 4x/wk consistently, hit 225 on bench for 5 which is a PR
nutrition is the weak point - skipping breakfast most days then overeating at night
going to move his protein target to 180g and add a breakfast
we'll start tracking steps, target 8k
he asked about adding a peptide for sleep - told him I'd flag it for the provider to review
rebook 4 weeks`,
  },
  {
    kind: "Check-in",
    channel: "Phone",
    notes: `quick call, 10 min
says the injections have been fine, no site reactions
appetite is down which is what we wanted
energy good, gym 3x this week
mentioned some mild joint pain in the right knee when squatting - not severe
told him to switch to leg press for now and we'll see
weight 198 at home scale
will send him the updated meal template today
follow up in 2 weeks`,
  },
  {
    kind: "Coach consult",
    channel: "Video",
    notes: `first consult since labs came back
went through the panel with her - thyroid is the story, TSH 5.8 with low free T3
she's been cold all the time, hair thinning, brain fog - all lines up
this is above my scope, flagging for Dr. Vale to review the thyroid picture
she's frustrated, has been told "labs are normal" elsewhere for years
explained the optimal vs reference range difference and she got it immediately
in the meantime: focus on protein, vitamin d, and sleep consistency
she wants to start training again - starting conservative, 3x full body
booking her with the provider this week`,
  },
  {
    kind: "Follow-up",
    channel: "In person",
    notes: `6 week follow up
labs recheck ordered
down 11 lbs total, waist down 2 inches
says libido is noticeably better, sleeping through the night now
strength up across the board
one issue - he's been skipping the weekend doses, says he forgets
set up a reminder in the app
also going to reorder his protocol, current supply runs out in 9 days
wants to add a second scan before his beach trip
very happy overall, asked about referring his brother`,
  },
  {
    kind: "Intake",
    channel: "In person",
    notes: `new member intake
41M, works in sales, high stress, 2 kids
primary goal is fat loss and energy, secondary is libido
history: gained about 35 lbs over 5 years, was athletic in college
sleeps ~5.5 hrs, 3 coffees before noon
no current training, walks the dog
diet is mostly takeout, admits he doesn't cook
no known conditions, not on any medication
ordering the full panel today
scan booked for next week
starting with steps and one habit - protein at breakfast
will build the full plan once labs are back`,
  },
  {
    kind: "Check-in",
    channel: "Messaging",
    notes: `texted to check in
says everything is going well
down another 2 lbs
no complaints, no side effects
keeping the same plan
next scan in 3 weeks`,
  },
];

const NOW_MS = absolute("2026-06-12T09:00:00").getTime();

function buildConsult(
  clientId: string,
  authorId: string,
  template: (typeof NOTE_TEMPLATES)[number],
  index: number,
  daysAgo: number,
  signed: boolean,
): Consult {
  const startedAt = absolute(NOW_MS - daysAgo * 86_400_000).toISOString();
  const summary = summarizeConsult(template.notes);
  const provenance = stampFor(template.notes, startedAt);

  return {
    id: `con-${clientId.slice(-3)}-${index}`,
    clientId,
    authorId,
    kind: template.kind,
    channel: template.channel,
    status: signed ? "Signed" : "Awaiting review",
    startedAt,
    endedAt: startedAt,
    durationMin: template.channel === "Messaging" ? 4 : template.channel === "Phone" ? 12 : 35,
    rawNotes: template.notes,
    aiSummary: summary,
    aiProvenance: provenance,
    // A signed consult's final summary is the AI's, accepted as-is unless the
    // coach edited it — editedFields() surfaces the difference in the UI.
    finalSummary: signed ? summary : undefined,
    signedAt: signed ? startedAt : undefined,
    signedBy: signed ? authorId : undefined,
    addenda: [],
    visibleToClient: signed,
  };
}

export const consults: Consult[] = clients.flatMap((c) => {
  const rand = seededRandom(c.id + "consults");
  // Roughly: active members have a richer consult history than leads.
  const count =
    c.status === "Active Protocol" || c.status === "Follow-Up Due"
      ? 2 + Math.floor(rand() * 3)
      : c.status === "Lead"
        ? 0
        : 1 + Math.floor(rand() * 2);

  return Array.from({ length: count }, (_, i) => {
    const template = NOTE_TEMPLATES[Math.floor(rand() * NOTE_TEMPLATES.length)];
    const daysAgo = 4 + i * 28 + Math.floor(rand() * 10);
    // The most recent consult on some members is deliberately left unsigned so
    // the review queue has real work in it.
    const signed = i > 0 || rand() > 0.28;
    return buildConsult(c.id, c.coachId, template, i + 1, daysAgo, signed);
  });
});

export const consultsByClient: Record<string, Consult[]> = consults.reduce(
  (acc, c) => {
    (acc[c.clientId] ??= []).push(c);
    return acc;
  },
  {} as Record<string, Consult[]>,
);

/** Newest first — how every surface displays them. */
export function consultsForClient(clientId: string): Consult[] {
  return [...(consultsByClient[clientId] ?? [])].sort((a, b) =>
    b.startedAt.localeCompare(a.startedAt),
  );
}

export function latestConsult(clientId: string): Consult | undefined {
  return consultsForClient(clientId)[0];
}

/** Consults a coach still owes a signature on. Drives the coach's Today queue. */
export function unsignedConsultsFor(coachId: string): Consult[] {
  return consults
    .filter((c) => c.authorId === coachId && c.status !== "Signed")
    .sort((a, b) => b.startedAt.localeCompare(a.startedAt));
}

export const NOTE_TEMPLATE_SAMPLES = NOTE_TEMPLATES.map((t) => t.notes);
