import { clients } from "@/lib/mock/clients";
import { staff } from "@/lib/mock/staff";
import {
  capacitySummary,
  utilisationByLocation,
  utilisationByProvider,
  utilisationByHour,
  capacityWindow,
  BOTTLENECK_THRESHOLD,
  type UtilisationCell,
  type ProviderCell,
} from "@/lib/analytics/capacity";

/**
 * CAPACITY, FOR AN OWNER — and the one number on this console that looks
 * measured, is measured, and still must not be read.
 *
 * ---------------------------------------------------------------------------
 * THE PROBLEM
 * ---------------------------------------------------------------------------
 * `lib/analytics/capacity.ts` is the best analytics module in the repo. Its
 * arithmetic is correct, it refuses to clamp utilisation over 100%, and it
 * counts bookings against unrostered clinicians separately instead of hiding
 * them. Run it against this build and it returns:
 *
 *     rostered   864.0 h/week      booked   33.8 h/week      utilisation  3.9%
 *
 * Every one of those numbers is real arithmetic over real records. And 3.9% is
 * a catastrophic figure — it is the number you would show a board before
 * closing three locations.
 *
 * It is also meaningless, and the reason is a seam between two fixtures rather
 * than anything about Alpha Health. `lib/mock/shifts.ts` generates a full weekly
 * roster for all staff across all five sites, which is sized for the real
 * clinic: 5,000+ members. `lib/analytics/attendance.ts` generates a booking
 * history from the 500 seeded members, producing ~112 bookings in the pinned
 * week. A denominator scaled for 5,000 people over a numerator scaled for 500
 * yields a ratio that describes the fixtures and nothing else.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS IS THE MOST DANGEROUS FIGURE ON THE CONSOLE
 * ---------------------------------------------------------------------------
 * `+ 12000` in `lib/analytics.ts` is a fabrication, and fabrications are at
 * least *findable* — someone reads the file and the constant is right there. A
 * correct computation over mismatched inputs has no constant to find. It passes
 * code review, it passes a provenance audit, and it would earn a MEASURED chip
 * honestly. "Measured" is not the same claim as "true", and this figure is the
 * proof: provenance labelling alone would have shipped it.
 *
 * ---------------------------------------------------------------------------
 * WHAT THIS MODULE DOES ABOUT IT
 * ---------------------------------------------------------------------------
 * It does not hide the number and it does not quietly rescale it — inventing a
 * correction factor to make 3.9% look plausible would be the same crime as the
 * magic constant, with better manners. Instead `scaleCheck()` derives, from the
 * fixtures themselves, whether the absolute ratio is safe to read, and the UI
 * refuses to render it as a headline when it is not. What remains after that
 * refusal is genuinely decision-grade and is what the page leads with:
 *
 *   - RELATIVE LOAD between locations and between clinicians. Both sides of the
 *     ratio are wrong by the same factor, so the ranking survives even though
 *     the level does not.
 *   - HOUR-OF-DAY SHAPE. Where the queue forms is scale-invariant.
 *   - UNROSTERED HOURS. An absolute count of a real defect, unaffected by the
 *     mismatch, and one nothing else in the app surfaces.
 */

/**
 * Below this, an absolute utilisation figure is not decision-grade.
 *
 * 25% is not a clinical or statistical constant — it is the level below which a
 * staffed, open clinic cannot plausibly be operating, which makes it a fixture
 * defect rather than a business finding. Set as a named threshold so the page
 * cannot decide this for itself and drift.
 */
export const DECISION_GRADE_FLOOR = 0.25;

export interface ScaleCheck {
  /** True when the absolute utilisation percentage may be shown as a headline. */
  decisionGrade: boolean;
  rosteredHours: number;
  bookedHours: number;
  bookingCount: number;
  utilisation: number;
  memberCount: number;
  staffCount: number;
  /** Why the absolute figure cannot be read, if it cannot. Empty when it can. */
  reason: string;
  /** What would have to change for the figure to become readable. */
  remedy: string;
}

export function scaleCheck(): ScaleCheck {
  const s = capacitySummary("all");
  const decisionGrade = s.utilisation >= DECISION_GRADE_FLOOR;

  return {
    decisionGrade,
    rosteredHours: s.availableHours,
    bookedHours: s.bookedHours,
    bookingCount: s.bookingCount,
    utilisation: s.utilisation,
    memberCount: clients.length,
    staffCount: staff.length,
    reason: decisionGrade
      ? ""
      : `The roster and the booking history are generated by two fixtures at different scales. lib/mock/shifts.ts rosters ${staff.length} staff across five sites for ${s.availableHours.toFixed(0)} hours this week — sized for the real clinic's 5,000+ members. lib/analytics/attendance.ts generates bookings for the ${clients.length} seeded members, producing ${s.bookingCount} in the same week. The ratio describes that mismatch, not Alpha Health.`,
    remedy:
      "Real appointment records against the real roster. Until then, read the ranking between locations and clinicians — both sides of every ratio are wrong by the same factor, so relative load survives — and read unrostered hours, which is an absolute count and is unaffected.",
  };
}

/**
 * Load ranking, expressed as share rather than as a ratio against roster.
 *
 * `share` is a location's booked hours as a fraction of all booked hours, which
 * is scale-invariant: it does not touch the roster denominator at all, so the
 * fixture mismatch cannot reach it. This is the honest way to answer "where is
 * the clinic busiest" in this build.
 *
 * `utilisation` is carried through untouched for a reader who wants it, but it
 * is never the sort key and never the headline.
 */
export interface LoadRow extends UtilisationCell {
  share: number;
}

export function loadByLocation(): LoadRow[] {
  const rows = utilisationByLocation();
  const total = rows.reduce((s, r) => s + r.bookedHours, 0) || 1;
  return rows
    .map((r) => ({ ...r, share: r.bookedHours / total }))
    .sort((a, b) => b.share - a.share);
}

/**
 * Per-clinician load. NOT a leaderboard, and the distinction is load-bearing.
 *
 * `docs/audit/ENGAGEMENT.md` records that this codebase deliberately avoids
 * ranking people against one another, and the argument transfers from members
 * to staff without modification: a ranked list of clinicians converts a
 * ROSTERING fact into a PERFORMANCE verdict. A provider at the bottom of this
 * list is not underperforming — they are rostered onto a quiet site, or into
 * hours the front desk cannot fill, or they carry the long appointments. None
 * of that is visible in the ratio, and all of it is invisible to whoever reads
 * the ranking as a scoreboard.
 *
 * So this is sorted by ABSOLUTE BOOKED HOURS, descending — a workload fact, not
 * a quality judgement — and the surface renders `openHours` beside it so the
 * question the page answers is "who has room" rather than "who is best".
 *
 * REJECTED: sorting by utilisation descending. It is the same list, and it
 * reads as a rank the moment a percentage sits at the end of each row.
 */
export function loadByProvider(): ProviderCell[] {
  return utilisationByProvider("all")
    .filter((p) => p.availableHours > 0 || p.bookingCount > 0)
    .sort((a, b) => b.bookedHours - a.bookedHours || a.label.localeCompare(b.label));
}

/** Hour-of-day shape — where the queue forms. Scale-invariant, so safe to read. */
export function hourShape() {
  const rows = utilisationByHour("all");
  const peak = Math.max(...rows.map((r) => r.bookedHours), 0) || 1;
  return rows.map((r) => ({ ...r, intensity: r.bookedHours / peak }));
}

export { capacityWindow, BOTTLENECK_THRESHOLD };
